### ISSUE TITLE
[Bug] Deleting "duplicate" files

### ISSUE THREAD

**Issue by schmeat** [szapp/filen-photo-organizer#1]
Hi,

I tried to run the action and it seems to just be deleting all the photos in my root camera upload folder. It says it's deleting the file because it's a duplicate, but there are no duplicates in the camera folder.

 I tested this using .DNG and .jpg photos.

# Actions
<img width="302" alt="Screenshot 2024-07-24 205857" src="https://github.com/user-attachments/assets/07c30368-3da5-4f5a-b9d4-f4c313714418">

<img width="511" alt="Screenshot 2024-07-24 210424" src="https://github.com/user-attachments/assets/23cf6ed8-725e-4aeb-9bb4-600f38045839">

# Variables
<img width="590" alt="Screenshot 2024-07-24 210127" src="https://github.com/user-attachments/assets/035b171d-cd92-4deb-96d7-674588d66236">

**Comment by szapp** [comment]
Hi! Thanks for the report with the screenshots!

This might happen, when source and destination directory are the same, resulting in the target file already existing (itself).

In your variables, try explicitly providing `DIR_PATTERN` (and `FILE_PATTERN`) as well.

**Comment by schmeat** [comment]
No data lost, I have it saved in a bunch of spots. You are right, when I added the variables it works. The readme might need to be updated. Thanks for your help and quick response!

**Comment by szapp** [comment]
@schmeat Glad it's resolved. Thanks a lot for pointing that out. I should definitely update the readme!
